controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Author;
use app\models\Subscribe;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;

class SiteController extends Controller
{

	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					['allow' => true, 'actions' => ['login', 'logout', 'index', 'author', 'report', 'subscribe']],
					[
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
			'verbs'  => [
				'class'   => VerbFilter::className(),
				'actions' => [
					'logout' => ['post'],
				],
			],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function actions()
	{
		return [
			'error'   => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class'           => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST? 'testme': null,
			],
		];
	}

	/**
	 * Displays homepage.
	 * @return string
	 */
	public function actionIndex()
	{
		$authors = Author::find()->all();
		return $this->render('index', compact('authors'));
	}

	public function actionAuthor($id)
	{
		if (!$author = Author::findOne($id)) {
			throw new NotFoundHttpException('Author not found');
		}

		$provider = new ActiveDataProvider([
			'query'      => $author->getBooks(),
			'pagination' => [
				'pageSize' => 50,
			],
			'sort'       => [
				'defaultOrder' => [
					'isbn' => SORT_DESC,
				],
			],
		]);
		return $this->render('author', compact('provider', 'author'));
	}

	/**
	 * Login action.
	 * @return Response|string
	 */
	public function actionLogin()
	{
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new LoginForm();
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->goBack();
		}
		return $this->render('login', [
			'model' => $model,
		]);
	}

	/**
	 * Logout action.
	 * @return Response
	 */
	public function actionLogout()
	{
		Yii::$app->user->logout();

		return $this->goHome();
	}

	public function actionReport($year)
	{
		$authors = Author::getTopOfTheYear($year);
		return $this->render('report', compact('authors'));
	}

	public function actionSubscribe($id)
	{
		$model = new Subscribe(['authorId' => $id]);
		if ($model->load(Yii::$app->request->post()) && $model->subscribe()) {
			Yii::$app->session->setFlash('subscribe');
		}
		return $this->render('subscribe', compact('model'));
	}
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Авторы', 'url' => ['/site/index']],
            ['label' => 'ТОП 1990', 'url' => ['/site/report', 'year' => 1990]],
            ['label' => 'ТОП 1991', 'url' => ['/site/report', 'year' => 1991]],
            ['label' => 'ТОП 1992', 'url' => ['/site/report', 'year' => 1992]],
            ['label' => 'ТОП 1993', 'url' => ['/site/report', 'year' => 1993]],
            ['label' => 'ТОП 1994', 'url' => ['/site/report', 'year' => 1994]],
            ['label' => 'ТОП 1995', 'url' => ['/site/report', 'year' => 1995]],
            ['label' => 'ТОП 1996', 'url' => ['/site/report', 'year' => 1996]],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>